### ISSUE TITLE
Can't get the grasp on how excel files work on this project

### ISSUE THREAD

**Issue by roostaamir** [mikhailshilkov/FsPokerLogic#2]
Hi
I was trying to start learning F# as a functional first language and I wanted to learn it further by a practical example. I saw your project and loved the idea, especially the fact that it has akka.net integration.
But my problem is that I cannot see how the project flow works and I cannot figure out how the excel files are working in your project. The code reads some "Rules" within the code (that I found) but I couldn't find a piece of code that is actually writing to these files. Could you kindly guide me through this process a little bit?
Thanks in advance

**Comment by mikhailshilkov** [comment]
Hi, the files are written manually by a human + some other tools, which are not part of this solution

**Comment by roostaamir** [comment]
Could I at least have a sample file or something to know what is going on with the logic?

**Comment by mikhailshilkov** [comment]
Believe me, it won't help you much. It is full of abbreviations, cryptic notations and numbers, numbers. It only makes sense to people who fill it in, and is really hard to learn.
And I don't have a permission to publish "production" files.

If your goal is to study F# usage, I would you looking at other parts of the solution.

**Comment by roostaamir** [comment]
Oh, I thought that the files actually make the logic more understandable
Thank you for your kind reply
